name: CI/CD Python Django

on:
  push:
    branches:
      - main

jobs:
  backend:
    name: Build and Deploy Django Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Build Docker image
        run: |
          docker build -t django-board-game .

      - name: Save Docker image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: ./django-board-game

      - name: Copy Docker image to EC2 and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          EC2_IP: ${{ secrets.EC2_IP }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no ubuntu@$EC2_IP << 'EOF'
            docker pull django-board-game
            docker stop $(docker ps -q --filter ancestor=django-board-game)
            docker run -d -p 8000:8000 django-board-game
          EOF
