name: CI/CD Python Django

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Package Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Clean up existing containers and images
        run: |
          docker container prune -f
          docker image prune -a -f

      - name: Build Docker image
        run: docker build --no-cache -t django-board-game .

      - name: Save Docker image to tarball
        run: docker save django-board-game -o django-board-game.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: django-board-game.tar

  deploy:
    name: Download & Deploy on EC2
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: .

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            docker container prune -f
            docker image prune -a -f
            docker load -i ./django-board-game.tar

            docker run -d \
              --name board-game-app \
              -e DB_HOST="${{ secrets.DB_HOST }}" \
              -e DB_PORT="${{ secrets.DB_PORT }}" \
              -e DB_NAME="${{ secrets.DB_NAME }}" \
              -e DB_USER="${{ secrets.DB_USER }}" \
              -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              -e DB_SSLMODE="${{ secrets.DB_SSLMODE }}" \
              -e ALLOWED_HOSTS="${{ secrets.ALLOWED_HOSTS }}" \
              -e DJANGO_DEBUG="${{ secrets.DJANGO_DEBUG }}" \
              -p 8000:8000 \
              django-board-game
