name: CI/CD Python Django

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Package Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          docker build -t django-board-game .

      - name: Save Docker image to tarball
        run: |
          docker save django-board-game -o django-board-game.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: django-board-game.tar

  deploy:
    name: Download & Deploy on EC2
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: .

      - name: Copy tarball to EC2 and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          EC2_IP: ${{ secrets.EC2_IP }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          scp -o StrictHostKeyChecking=no django-board-game.tar ubuntu@$EC2_IP:/home/ubuntu/

          ssh -o StrictHostKeyChecking=no ubuntu@$EC2_IP << 'EOF'
            docker load -i /home/ubuntu/django-board-game.tar
            docker stop $(docker ps -q --filter ancestor=django-board-game) || true
            docker run -d -p 8000:8000 django-board-game
          EOF
